Repository kaushik-rishi/rocketcp, pull requests merged in 2021-05, with the labels that each got.

#154 Added a advance template for cpp
  src/templates/codes/cppAdv.txt
Labels: GSSOC21, Level3

#165 Removed unnesecary check in dir option
  src/serverUtils/argParser.js
Labels: GSSOC21, Level3

#168 Url parser
  package-lock.json
  package.json
  src/configuration/server.js
  src/serverUtils/argParser.js
  src/serverUtils/protocol.js
Labels: GSSOC21, Level3

#177 added lang query parser in url parser
  src/serverUtils/protocol.js
Labels: GSSOC21, Level3

#178 Url parser dir
  src/serverUtils/protocol.js
Labels: GSSOC21, Level3

#179 Url parser watch
  src/serverUtils/protocol.js
Labels: GSSOC21, Level3

#180 Url parser interactive
  src/serverUtils/protocol.js
Labels: Level3

#187 Corrected typo in Readme
  README.md
Labels: GSSOC21, Level2
